
HADOOP:
  - config_type: core-site
    hadoop.ssl.require.client.cert: false
    hadoop.ssl.hostname.verifier: DEFAULT
    hadoop.ssl.keystores.factory.class: org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory
    hadoop.ssl.server.conf: ssl-server.xml
    hadoop.ssl.client.conf: ssl-client.xml

  - config_type: ssl-server
    ssl.server.keystore.keypassword: $keystorepassword
    ssl.server.keystore.password: $keystorepassword
    ssl.server.keystore.location: $keystore
    ssl.server.truststore.location: $truststore
    ssl.server.truststore.password: $truststorepassword

  - config_type: ssl-client
    ssl.client.keystore.location: $keystore
    ssl.client.keystore.password: $keystorepassword
    ssl.client.truststore.location: $truststore
    ssl.client.truststore.password: $truststorepassword

HDFS:
  - config_type: core-site
    hadoop.rpc.protection: privacy

  - config_type: hdfs-site
    dfs.encrypt.data.transfer: true
    dfs.encrypt.data.transfer.algorithm: 3des

HDFSUI:
  - config_type: hdfs-site
    dfs.http.policy: HTTPS_ONLY
    dfs.namenode.https-address: 0.0.0.0:50470
    dfs.namenode.secondary.https-address: 0.0.0.0:50091

MRSHUFFLE:
  - config_type: mapred-site
    mapreduce.shuffle.ssl.enabled: true

MAPREDUCE2UI:
  - config_type: mapred-site
    mapreduce.jobhistory.http.policy: HTTPS_ONLY
    mapreduce.jobhistory.webapp.https.address: 0.0.0.0:19890
    mapreduce.jobhistory.webapp.address: 0.0.0.0:19890

  - config_type: hdfs-site
    dfs.https.enable: true

YARN:
  - config_type: yarn-site
    yarn.http.policy: HTTPS_ONLY
    yarn.log.server.url: $historyserver
    yarn.log.server.web-service.url: $timelineserver
    yarn.nodemanager.webapp.https.address: 0.0.0.0:8044

  - config_type: hdfs-site
    dfs.https.enable: true

TEZ:
  - config_type: tez-site
    tez.runtime.shuffle.ssl.enable: true
    tez.runtime.shuffle.keep-alive.enabled: true


KAFKA:
  - config_type: kafka-broker
    ssl.keystore.location: $keystore
    ssl.keystore.password: $keystorepassword
    ssl.key.password: $keystorepassword
    ssl.truststore.location: $truststore
    ssl.truststore.password: $truststorepassword

HIVE:
  - config_type: hive-site
    hive.server2.use.SSL: true
  - config_type: hiveserver2-site
    hive.server2.use.SSL: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword

ZEPPELIN:
  - config_type: zeppelin-config
    zeppelin.ssl: true
    zeppelin.ssl.client.auth: false
    zeppelin.ssl.key.manager.password: $keystorepassword
    zeppelin.ssl.keystore.password: $keystorepassword
    zeppelin.ssl.keystore.path: $keystore
    zeppelin.ssl.keystore.type: JKS
    zeppelin.ssl.truststore.password: $truststorepassword
    zeppelin.ssl.truststore.path: $keystore
    zeppelin.ssl.truststore.type: JKS

AMBARI_INFRA:
  - config_type: infra-solr-env
    infra_solr_ssl_enabled: true
    infra_solr_keystore_location: $keystore
    infra_solr_keystore_password: $keystorepassword
    infra_solr_truststore_location: $truststore
    infra_solr_truststore_password: $truststorepassword

RANGERADMIN:
  - config_type: ranger-admin-site
    ranger.service.http.enabled: false
    ranger.https.attrib.keystore.file: $keystore
    ranger.service.https.attrib.keystore.pass: $keystorepassword
    ranger.service.https.attrib.keystore.keyalias: nifi-key
    ranger.service.https.attrib.clientAuth: want
    ranger.service.https.attrib.ssl.enabled: true
    ranger.service.https.port: 6182
    ranger.truststore.alias: nifi-cert
    ranger.truststore.file: $truststore
    ranger.truststore.password: $truststorepassword

  - config_type: ranger-site
    ranger.service.https.attrib.keystore.file: $keystore
    ranger.service.https.attrib.client.auth: want

  - config_type: ranger-tagsync-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-ugsync-site
    ranger.usersync.truststore.file: $truststore
    ranger.usersync.truststore.password: $truststorepassword
    ranger.usersync.keystore.file: $keystore
    ranger.usersync.keystore.password: $keystorepassword

RANGERPLUGINS:
  - config_type: ranger-hdfs-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-yarn-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-hive-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-hbase-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-atlas-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-knox-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-storm-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-kafka-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

HBASE:
  - config_type: hbase-site
    hbase.ssl.enabled: true
    hadoop.ssl.enabled: true
    ssl.server.keystore.keypassword: $keystorepassword
    ssl.server.keystore.password: $keystorepassword
    ssl.server.keystore.location: $keystore

ATLAS:
  - config_type: application-properties
    atlas.enableTLS: true
    keystore.file: $keystore
    truststore.file: $truststore
    client.auth.enabled: true
    cert.stores.credential.provider.path: jceks://file//etc/security/certificates/ssl.jceks

SPARK:
  - config_type: yarn-site
    spark.authenticate: true

  - config_type: spark-defaults
    spark.authenticate: true
    spark.authenticate.enableSaslEncryption: true
    spark.ssl.enabled: true
    spark.ssl.keyPassword: $keystorepassword
    spark.ssl.keyStore: $keystore
    spark.ssl.keyStorePassword: $keystorepassword
    spark.ssl.protocol: TLS
    spark.ssl.trustStore: $truststore
    spark.ssl.trustStorePassword: $truststorepassword

  - config_type: spark-hive-site-override
    hive.server2.transport.mode: http
    hive.server2.thrift.http.port: 10015
    hive.server2.http.endpoint: cliservice
    hive.server2.use.SSL: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword

  - config_type: livy-conf
    livy.keystore: $keystore
    livy.keystore.password: $keystorepassword
    livy.key-password: $keystorepassword

SPARK2:
  - config_type: yarn-site
    spark.authenticate: true

  - config_type: spark2-defaults
    spark.authenticate: true
    spark.authenticate.enableSaslEncryption: true
    spark.ssl.enabled: true
    spark.ssl.keyPassword: $keystorepassword
    spark.ssl.keyStore: $keystore
    spark.ssl.keyStorePassword: $keystorepassword
    spark.ssl.protocol: TLS
    spark.ssl.trustStore: $truststore
    spark.ssl.trustStorePassword: $truststorepassword
    spark.ui.https.enabled: true
    spark.ssl.historyServer.port: 18481

  - config_type: spark2-hive-site-override
    hive.server2.transport.mode: http
    hive.server2.thrift.http.port: 10016
    hive.server2.http.endpoint: cliservice
    hive.server2.use.SSL: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword

  - config_type: livy2-conf
    livy.keystore: $keystore
    livy.keystore.password: $keystorepassword
    livy.key-password: $keystorepassword

STORM:
  - config_type: storm-site
    ui.https.port: 8740
    ui.https.keystore.type: jks
    ui.https.keystore.path: $keystore
    ui.https.keystore.password: $keystorepassword
    ui.https.key.password: $keystorepassword
    ui.https.truststore.path: $truststore
    ui.https.truststore.password: $truststorepassword
    ui.https.truststore.type: jks
    drpc.https.port: 3778
    drpc.https.keystore.type: jks
    drpc.https.keystore.path: $keystore
    drpc.https.keystore.password: $keystorepassword
    drpc.https.key.password: $keystorepassword
    drpc.https.truststore.path: $truststore
    drpc.https.truststore.password: $truststorepassword
    drpc.https.truststore.type: jks

FALCON:
  - config_type: falcon-startup.properties
    "*.falcon.enableTLS": true
    "*.keystore.file": $keystore
    "*.keystore.password": $keystorepassword

  - config_type: falcon-env
    falcon_port: 15443
